{% set name = "chemicalite" %}
{% set version = "2024.05.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rvianello/chemicalite/archive/refs/tags/{{ version }}.tar.gz
  sha256: df44ab0a2081f86692d92625efd320e0fb7d13eb9a988232be1fb6ee057c4165

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - cmake
    - make  # [unix]
    - sed  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - sqlite
    - rdkit ==2024.03.4
    - libboost-devel
    - eigen
    - catch2
    - zlib
  run:
    - sqlite
    - {{ pin_compatible('rdkit', max_pin='x.x.x') }}

test:
  commands:
    - echo ".load chemicalite" | sqlite3

about:
  home: https://github.com/rvianello/chemicalite
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'An SQLite extension for chemoninformatics applications'
  doc_url: https://chemicalite.readthedocs.io/
  dev_url: https://github.com/rvianello/chemicalite

extra:
  recipe-maintainers:
    - rvianello
